
default: serve

.PHONY: serve
serve:
	@echo ""
	@echo "==> Serving Jekyll site"
	bundle exec jekyll serve

.PHONY: update
update:
	@echo ""
	@echo "==> Updating the GitHub Pages dependencies"
	bundle update
